In [ ]:
#numpy


In [2]:
import numpy as np
import pandas as pd

In [6]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.concatenate((x,y),axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
z=np.concatenate((x,y),axis=1)
z

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [8]:
a=np.arange(6).reshape(1,6)
print(a)
a.shape

[[0 1 2 3 4 5]]


(1, 6)

In [16]:
a=np.array([2,0,1,8])
a.shape:(4,)
a2=a[np.newaxis,:]    #row vector
a2


array([[2, 0, 1, 8]])

In [15]:
a3=a[:,np.newaxis]    #column vector
a3

array([[2],
       [0],
       [1],
       [8]])

In [17]:
a2=a[np.newaxis,1:3]
a2

array([[0, 1]])

In [29]:
a=np.array([[1,2,3],[4,5,6]])
b=np.expand_dims(a,axis=0)
print(b)
b.shape

[[[1 2 3]
  [4 5 6]]]


(1, 2, 3)

In [26]:
a=np.array([[1,2,3],[4,5,6]])
b=np.expand_dims(a,axis=1)
print(b)
b.shape

[[[1 2 3]]

 [[4 5 6]]]


(2, 1, 3)

In [28]:
a=np.array([[1,2,3],[4,5,6]])
b=np.expand_dims(a,axis=2)
print(b)
b.shape

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


(2, 3, 1)

In [32]:
data=np.array([1,2,3])   #INDEXING AND SLICING.....
data[1]


array([1, 2])

In [33]:
data[0:2]

array([1, 2])

In [34]:
data[1:]

array([2, 3])

In [35]:
data[-2:]

array([2, 3])

In [3]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
(a[a<7])


array([1, 2, 3, 4, 5, 6])

In [ ]:
#array


In [2]:
import numpy as np

In [45]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
<class 'numpy.ndarray'>


In [47]:
print(arr.shape)


(12,)


In [48]:
x=arr.reshape(2,3,2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [11]:
print(arr[1])

2


In [31]:
print(arr[1:5:2])
print(arr[1:])

[2 4]
[2 3 4 5]


In [55]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [58]:
y=arr.reshape(-1)
print(y)

[1 2 3 4 5 6]


In [19]:
print(arr[1,1])
print(arr[1,-1])

5
6


In [37]:
print(arr.shape)

(2, 3)


In [35]:
print(arr[1,1:3])
print(arr[0:2,2])

[5 6]
[3 6]


In [21]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [22]:
print(arr[0,1,2])
print(arr[1,0,1])

6
2


In [59]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [61]:
arr1=np.array([1,2,3])    #stack(axis)=concatenate...
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]
